var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var NbaLogSchema = new mongoose.Schema({
  Player : String,
  Tm : String,
  Date : String,
  Rk : String,
  Age : String,
  Pos : String,
  Home : String,
  Opp : String,
  "W/L" : String,
  GS : String,
  MP : String,
  FG : String,
  FGA : String,
  "FG%" : String,
  "2P ": String,
  "2PA ": String,
  "2P%" : String,
  "3P" : String,
  "3PA ":String,
  "3P% ": String,
  FT : String,
  FTA :String,
  "FT%" : String,
  ORB : String,
  DRB :String,
  TRB : String,
  AST : String,
  STL : String,
  BLK : String,
  TOV : String,
  PF : String,
  PTS : String,
  GmSc :String,
  Line : String,
 " O/U" : String,
  DK: String,
  FD: String,
},
{ collection: 'Nba1415'});

mongoose.model("NbaLog", NbaLogSchema);